[features]
seeds = false
skip-lint = false
[programs.localnet]
escrow = "GJTaHeCtstyWdj2pHUrjHXFKmcFQ4tgoNDSrtAcbcbNo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/arunavoray/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
